version: "3.8"

services:
  db:
    container_name: auction-db
    image: postgres:15.0-alpine
    volumes:
      - "./database/auction-db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: auction-db
    ports:
      - "5460:5432"
    restart:
      unless-stopped
      